# Generated by Django 4.0.3 on 2023-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_marker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'type_marker',
                'verbose_name_plural': 'type_markers',
                'ordering': ['-created'],
            },
        ),
    ]
