# Generated by Django 4.0.3 on 2023-02-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='decription',
            field=models.CharField(max_length=500),
        ),
    ]
