# Generated by Django 4.0.3 on 2023-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_marker_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='decription',
            field=models.TextField(max_length=500),
        ),
    ]
