# Generated by Django 4.0.3 on 2023-02-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_marker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='image',
        ),
    ]
