# Generated by Django 4.0 on 2023-07-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_marker_typ_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='typ_e',
        ),
    ]
