# Generated by Django 4.0 on 2023-07-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_marker_typ_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='typ_e',
            field=models.ManyToManyField(related_name='type_marker', to='map.TypeMarker'),
        ),
    ]
